(()=>{"use strict";
const $=id=>document.getElementById(id),icons={k:"♚",q:"♛",r:"♜",b:"♝",n:"♞",p:"♟"},names={w:{k:"Anduin",q:"Jaina",r:"Uther",b:"Tyrande",n:"Arthas",p:"Lothar"},b:{k:"Thrall",q:"Sylvanas",r:"Garrosh",b:"Vol'jin",n:"Rexxar",p:"Saurfang"}},values={p:100,n:320,b:330,r:500,q:900,k:20000};
function characterArt(faction,type){
 const ally=faction==="w", primary=ally?"#2868b5":"#922d29",edge=ally?"#e6c36e":"#b6a4a0",skin=ally?"#e7b995":"#83a05c",dark=ally?"#112a55":"#381919",glow=ally?"#79caff":"#ff805c";
 const details={
 k:`<path d="M25 22 22 6 32 13 43 3 53 13 64 6 60 22Z" fill="${edge}" stroke="${dark}" stroke-width="2"/><path d="M32 13 43 19 54 13" fill="none" stroke="${glow}" stroke-width="3"/>`,
 q:`<path d="M23 25 18 8 30 16 43 3 55 16 68 8 63 25Z" fill="${dark}" stroke="${edge}" stroke-width="3"/><circle cx="43" cy="11" r="5" fill="${glow}"/><path d="M72 63 74 11M67 17 81 17" stroke="${edge}" stroke-width="4"/>`,
 r:`<path d="M22 25 22 7 32 7 32 14 39 14 39 7 48 7 48 14 56 14 56 7 65 7 65 25Z" fill="${edge}" stroke="${dark}" stroke-width="2"/><path d="M11 64 11 15 17 15 17 64" stroke="${edge}" stroke-width="4"/>`,
 b:`<path d="M23 29 18 11 35 20 43 4 51 20 68 11 63 29" fill="${dark}" stroke="${edge}" stroke-width="3"/><path d="M43 6 43 25" stroke="${glow}" stroke-width="3"/><path d="M74 65 76 15M68 24 84 24" stroke="${glow}" stroke-width="4"/>`,
 n:`<path d="M19 31 14 14 27 21 34 6 43 21 57 8 67 28" fill="${dark}" stroke="${edge}" stroke-width="3"/><path d="M70 64 77 26 83 17M72 27 85 30" stroke="${edge}" stroke-width="5" fill="none"/>`,
 p:`<path d="M28 27 25 16 34 20 43 11 52 20 61 16 58 27" fill="${dark}" stroke="${edge}" stroke-width="2"/><path d="M16 66 16 22M10 28 22 28" stroke="${edge}" stroke-width="4"/>`};
 const orc=ally?'':`<path d="M27 43 20 36 30 38M58 43 66 36 56 38" fill="#f6e8c9" stroke="#342a22" stroke-width="1.4"/>`;
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 86 100" role="img"><defs><linearGradient id="a" x2="1" y2="1"><stop stop-color="${primary}"/><stop offset="1" stop-color="${dark}"/></linearGradient></defs><ellipse cx="43" cy="92" rx="34" ry="6" fill="#080b16" opacity=".6"/><path d="M8 85 15 61 29 54 57 54 71 61 78 85 67 91 19 91Z" fill="url(#a)" stroke="${edge}" stroke-width="2.5"/><path d="M14 62 6 77 16 83 26 65M72 62 80 77 70 83 60 65" fill="${primary}" stroke="${edge}" stroke-width="2"/><path d="M29 55 43 72 57 55M43 72 43 88" fill="none" stroke="${edge}" stroke-width="3"/><path d="M29 27Q43 18 57 27L59 42Q56 55 43 58Q30 55 27 42Z" fill="${skin}" stroke="${dark}" stroke-width="2"/>${orc}<path d="M31 38 38 37M48 37 55 38" stroke="${dark}" stroke-width="2.5"/><circle cx="36" cy="40" r="1.7" fill="${glow}"/><circle cx="51" cy="40" r="1.7" fill="${glow}"/><path d="M38 49Q43 52 49 49" stroke="${dark}" fill="none" stroke-width="1.5"/>${details[type]}<path d="M35 77 43 82 51 77 43 73Z" fill="${glow}" stroke="${edge}" stroke-width="1"/><path d="M23 86H63" stroke="${edge}" stroke-width="2"/></svg>`;
 return "data:image/svg+xml;charset=utf-8,"+encodeURIComponent(svg);
}
let s,selected=null,flipped=false,mode=false,level=0,busy=false,pending=null,undoStack=[],moveLog=[];
const fresh=()=>({board:["rnbqkbnr","pppppppp","........","........","........","........","PPPPPPPP","RNBQKBNR"].map(x=>[...x].map(p=>p==="."?null:(p===p.toUpperCase()?"w":"b")+p.toLowerCase())),turn:"w",castle:{w:{k:true,q:true},b:{k:true,q:true}},ep:null,half:0,full:1,last:null,over:null});
const enemy=c=>c==="w"?"b":"w",inside=(r,c)=>r>=0&&r<8&&c>=0&&c<8,clone=x=>JSON.parse(JSON.stringify(x));
function attacked(g,r,c,by){const b=g.board;for(let y=0;y<8;y++)for(let x=0;x<8;x++){let p=b[y][x];if(!p||p[0]!==by)continue;let t=p[1],dy=r-y,dx=c-x;if(t==="p"){if(dy===(by==="w"?-1:1)&&Math.abs(dx)===1)return true;continue}if(t==="n"){if(Math.abs(dy)*Math.abs(dx)===2&&Math.abs(dy)+Math.abs(dx)===3)return true;continue}if(t==="k"){if(Math.max(Math.abs(dy),Math.abs(dx))===1)return true;continue}let straight=(dy===0||dx===0),diagonal=Math.abs(dy)===Math.abs(dx);if(!((t==="r"&&straight)||(t==="b"&&diagonal)||(t==="q"&&(straight||diagonal))))continue;let sy=Math.sign(dy),sx=Math.sign(dx),a=y+sy,z=x+sx,clear=true;while(a!==r||z!==c){if(b[a][z]){clear=false;break}a+=sy;z+=sx}if(clear)return true}return false}
function check(g,col){let king=null;for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(g.board[r][c]===col+"k")king=[r,c];return !king||attacked(g,king[0],king[1],enemy(col))}
function pseudo(g,r,c){let p=g.board[r][c];if(!p)return[];let col=p[0],t=p[1],b=g.board,out=[];const add=(y,x,extra={})=>{if(inside(y,x)&&(!b[y][x]||b[y][x][0]!==col)&&b[y][x]?.[1]!=="k")out.push({a:[r,c],z:[y,x],...extra})};if(t==="p"){let d=col==="w"?-1:1,start=col==="w"?6:1,end=col==="w"?0:7;if(inside(r+d,c)&&!b[r+d][c]){add(r+d,c,r+d===end?{promo:"q"}:{});if(r===start&&!b[r+2*d][c])add(r+2*d,c)}for(let dx of [-1,1]){let y=r+d,x=c+dx;if(!inside(y,x))continue;if(b[y][x]&&b[y][x][0]!==col)add(y,x,y===end?{promo:"q"}:{});else if(g.ep&&g.ep[0]===y&&g.ep[1]===x)add(y,x,{ep:true})}return out}
if(t==="n"){for(let [dy,dx] of [[1,2],[1,-2],[-1,2],[-1,-2],[2,1],[2,-1],[-2,1],[-2,-1]])add(r+dy,c+dx);return out}
if(t==="k"){for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)if(dy||dx)add(r+dy,c+dx);let row=col==="w"?7:0;if(r===row&&c===4&&!check(g,col)){if(g.castle[col].k&&b[row][7]===col+"r"&&!b[row][5]&&!b[row][6]&&!attacked(g,row,5,enemy(col))&&!attacked(g,row,6,enemy(col)))add(row,6,{castle:"k"});if(g.castle[col].q&&b[row][0]===col+"r"&&!b[row][1]&&!b[row][2]&&!b[row][3]&&!attacked(g,row,3,enemy(col))&&!attacked(g,row,2,enemy(col)))add(row,2,{castle:"q"})}return out}
let dirs=[];if(t==="r"||t==="q")dirs.push([1,0],[-1,0],[0,1],[0,-1]);if(t==="b"||t==="q")dirs.push([1,1],[1,-1],[-1,1],[-1,-1]);for(let [dy,dx] of dirs){let y=r+dy,x=c+dx;while(inside(y,x)){if(b[y][x]){if(b[y][x][0]!==col)add(y,x);break}add(y,x);y+=dy;x+=dx}}return out}
function apply(g,m){let h=clone(g),b=h.board,[r,c]=m.a,[y,x]=m.z,p=b[r][c],target=b[y][x];b[y][x]=p;b[r][c]=null;if(m.ep)b[r][x]=null;if(m.castle){let from=m.castle==="k"?7:0,to=m.castle==="k"?5:3;b[y][to]=b[y][from];b[y][from]=null}if(m.promo)b[y][x]=p[0]+m.promo;if(p[1]==="k"){h.castle[p[0]].k=false;h.castle[p[0]].q=false}if(p[1]==="r"){if(r===(p[0]==="w"?7:0)&&c===0)h.castle[p[0]].q=false;if(r===(p[0]==="w"?7:0)&&c===7)h.castle[p[0]].k=false}if(target?.[1]==="r"){let side=target[0],row=side==="w"?7:0;if(y===row&&x===0)h.castle[side].q=false;if(y===row&&x===7)h.castle[side].k=false}h.ep=p[1]==="p"&&Math.abs(y-r)===2?[(r+y)/2,c]:null;h.half=(p[1]==="p"||target||m.ep)?0:h.half+1;h.turn=enemy(g.turn);if(g.turn==="b")h.full++;h.last=[m.a,m.z];return h}
function legal(g,col=g.turn){let out=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(g.board[r][c]?.[0]===col)for(let m of pseudo(g,r,c))if(!check(apply(g,m),col))out.push(m);return out}
function assess(g){let lm=legal(g);if(!lm.length)return check(g,g.turn)?(g.turn==="b"?999999:-999999):0;let v=0;for(let row of g.board)for(let p of row)if(p)v+=(p[0]==="b"?1:-1)*values[p[1]];return v}
function aiPick(){let lm=legal(s),depth=level===0?1:2;function search(g,d,alpha,beta){if(!d||!legal(g).length)return assess(g);let maximizing=g.turn==="b",best=maximizing?-Infinity:Infinity;for(let m of legal(g)){let v=search(apply(g,m),d-1,alpha,beta);best=maximizing?Math.max(best,v):Math.min(best,v);if(maximizing)alpha=Math.max(alpha,best);else beta=Math.min(beta,best);if(beta<=alpha)break}return best}let scored=lm.map(m=>({m,v:search(apply(s,m),depth-1,-Infinity,Infinity)+Math.random()*(level===0?120:8)}));scored.sort((a,b)=>b.v-a.v);return scored[0]?.m}
function notation(m,g){let p=g.board[m.a[0]][m.a[1]],capture=!!g.board[m.z[0]][m.z[1]]||m.ep;return `${names[p[0]][p[1]]} ${"abcdefgh"[m.a[1]]}${8-m.a[0]}${capture?" × ":" → "}${"abcdefgh"[m.z[1]]}${8-m.z[0]}${m.promo?" = ♕":""}${m.castle?" (roque)":""}`}
function persist(){try{localStorage.setItem("azeroth-v2",JSON.stringify({s,mode,level,moveLog,undoStack,flipped}))}catch(e){}}
function finish(){let lm=legal(s);if(!lm.length)s.over=check(s,s.turn)?`Échec et mat · ${s.turn==="w"?"Horde":"Alliance"} gagne`:"Pat · partie nulle";else if(s.half>=100)s.over="Nulle · règle des 50 coups";else if(check(s,s.turn))s.over=null;else s.over=null}
function play(m){let before=clone(s);undoStack.push(before);moveLog.push(notation(m,s));s=apply(s,m);selected=null;finish();persist();render();if(mode&&s.turn==="b"&&!s.over){busy=true;setTimeout(()=>{let pick=aiPick();busy=false;if(pick)play(pick);else render()},280)}}
function render(){let el=$("board");el.innerHTML="";let lm=selected?legal(s).filter(m=>m.a[0]===selected[0]&&m.a[1]===selected[1]):[];for(let i=0;i<64;i++){let r=flipped?7-Math.floor(i/8):Math.floor(i/8),c=flipped?7-i%8:i%8,p=s.board[r][c],sq=document.createElement("div");sq.className="sq "+((r+c)%2?"dark":"light");if(selected?.[0]===r&&selected?.[1]===c)sq.classList.add("selected");let hit=lm.find(m=>m.z[0]===r&&m.z[1]===c);if(hit)sq.classList.add(p||hit.ep?"capture":"target");if(s.last?.some(a=>a[0]===r&&a[1]===c))sq.classList.add("last");if(p){let span=document.createElement("span");span.className="piece "+p[0];let portrait=document.createElement("img");portrait.src=characterArt(p[0],p[1]);portrait.alt=names[p[0]][p[1]]+" — "+({k:"roi",q:"reine",r:"tour",b:"fou",n:"cavalier",p:"pion"}[p[1]]);portrait.draggable=false;span.append(portrait);span.title=portrait.alt;sq.append(span)}if((flipped?c===7:c===0)){let a=document.createElement("span");a.className="coord rank";a.textContent=8-r;sq.append(a)}if((flipped?r===0:r===7)){let a=document.createElement("span");a.className="coord file";a.textContent="abcdefgh"[c];sq.append(a)}sq.onclick=()=>tap(r,c);el.append(sq)}
$("status").textContent=s.over||`${s.turn==="w"?"Alliance":"Horde"} joue${check(s,s.turn)?" · ÉCHEC !":""}`;$("badge").textContent=s.over?"TERMINÉ":mode?"CONTRE L'IA":"2 JOUEURS";$("mode").textContent=mode?"Contre l'IA":"2 joueurs";$("level").textContent=level?"IA : tactique":"IA : novice";$("log").innerHTML=moveLog.length?moveLog.map((x,i)=>`${i+1}. ${x}`).join("<br>"):"La bataille commence.";$("log").scrollTop=$("log").scrollHeight}
function tap(r,c){if(busy||s.over||(mode&&s.turn==="b"))return;let p=s.board[r][c];if(selected){let m=legal(s).find(m=>m.a[0]===selected[0]&&m.a[1]===selected[1]&&m.z[0]===r&&m.z[1]===c);if(m){if(m.promo){pending=m;promotion();return}play(m);return}}selected=p?.[0]===s.turn?[r,c]:null;render()}
function modal(title,text){$("modalTitle").textContent=title;$("modalText").textContent=text;$("promos").classList.add("hidden");$("dismiss").classList.remove("hidden");$("overlay").classList.remove("hidden")}
function promotion(){modal("Promotion","Choisis la nouvelle pièce de ton pion.");$("dismiss").classList.add("hidden");let el=$("promos");el.innerHTML="";el.classList.remove("hidden");for(let t of ["q","r","b","n"]){let b=document.createElement("button");b.className="btn gold";b.textContent=icons[t];b.onclick=()=>{let m={...pending,promo:t};pending=null;$("overlay").classList.add("hidden");play(m)};el.append(b)}}
$("dismiss").onclick=()=>$("overlay").classList.add("hidden");$("help").onclick=()=>modal("Guide du jeu","Règles classiques : déplacements légaux, échec, mat, pat, roque, prise en passant et promotion. Touchez une pièce puis sa destination. L'IA est locale et reste un adversaire de démonstration. Les noms des héros sont illustratifs ; aucun modèle ou illustration officiel n'est intégré.");
$("new").onclick=()=>{if(!confirm("Commencer une nouvelle partie ?"))return;s=fresh();moveLog=[];undoStack=[];selected=null;busy=false;persist();render()};
$("mode").onclick=()=>{if(moveLog.length&&!confirm("Changer de mode et recommencer la partie ?"))return;mode=!mode;s=fresh();moveLog=[];undoStack=[];selected=null;busy=false;persist();render()};
$("level").onclick=()=>{level=1-level;persist();render()};
$("flip").onclick=()=>{flipped=!flipped;persist();render()};
$("undo").onclick=()=>{if(busy)return;let count=mode&&s.turn==="w"?2:1;while(count--&&undoStack.length){s=undoStack.pop();moveLog.pop()}selected=null;persist();render()};
try{let data=JSON.parse(localStorage.getItem("azeroth-v2"));if(data?.s?.board){({s,mode,level,moveLog,undoStack,flipped}=data)}}catch(e){}if(!s)s=fresh();render();
})();